#!/bin/bash

echo "🎯 CosyVoice Deployment Guide"
echo "=============================="
echo ""
echo "Since the RunPod API endpoints are not accessible, let's use the web interface:"
echo ""
echo "1. 🌐 Go to: https://console.runpod.io/pods"
echo ""
echo "2. 🔧 Click 'Deploy' and use these settings:"
echo "   - Name: CosyVoice RTX A4000"
echo "   - Image: nvidia/cuda:12.1-devel-ubuntu22.04"
echo "   - GPU: RTX A4000"
echo "   - Container Disk: 50 GB"
echo "   - Volume Disk: 100 GB"
echo "   - Ports: 8000/http, 22/tcp"
echo "   - Start SSH: ✅ YES"
echo "   - Start Jupyter Lab: ❌ NO"
echo ""
echo "3. 🚀 After pod is running, run these commands in the terminal:"
echo ""
echo "   # Update system"
echo "   apt-get update"
echo "   apt-get install -y python3-pip git curl wget"
echo ""
echo "   # Install Python dependencies"
echo "   pip3 install torch torchaudio fastapi uvicorn numpy scipy librosa soundfile"
echo ""
echo "   # Clone CosyVoice"
echo "   cd /workspace"
echo "   git clone https://github.com/FunAudioLLM/CosyVoice.git"
echo "   cd CosyVoice"
echo "   pip3 install -r requirements.txt"
echo ""
echo "   # Start the server"
echo "   python3 -m http.server 8000 &"
echo ""
echo "4. 🌐 Access your CosyVoice at: https://[POD_ID]-8000.proxy.runpod.net"
echo ""
echo "Would you like me to help you with any specific step?"
